# dataset related params
IMG_SHAPE = [160, 160, 3]
DATASET_NAME = 'celeba'
DATASET_SIZE = 197011
DATASET_SPLIT = [0.7, 0.15, 0.15] # TRAIN, VAL, TEST 
LABEL_NAMES = [
    'Male',
    'Smiling',
    'Eyeglasses',
    'Young'
]
NUM_CLASSES  = len(LABEL_NAMES)
BATCH_SIZE   = 32

TRAIN_SIZE = int(DATASET_SIZE*DATASET_SPLIT[0])
VAL_SIZE   = int(DATASET_SIZE*DATASET_SPLIT[1])
TEST_SIZE  = int(DATASET_SIZE*DATASET_SPLIT[2])
TRAIN_SPLIT = TRAIN_SIZE
VAL_SPLIT   = TRAIN_SIZE+VAL_SIZE
TEST_SPLIT  = DATASET_SIZE

# model related params
DEPTH_MULTIPLIER = 0.5
DROPOUT_PROB = 0.2
