# dataset related params
IMG_SHAPE = [128, 128, 3]
DATASET_NAME = 'cifar-10'
DATASET_SIZE = 30000
DATASET_SPLIT = [0.7, 0.15, 0.15] # TRAIN, VAL, TEST 
NUM_CLASSES  = 10
BATCH_SIZE   = 32

TRAIN_SIZE = int(DATASET_SIZE*DATASET_SPLIT[0])
VAL_SIZE   = int(DATASET_SIZE*DATASET_SPLIT[1])
TEST_SIZE  = int(DATASET_SIZE*DATASET_SPLIT[2])
TRAIN_SPLIT = TRAIN_SIZE
VAL_SPLIT   = TRAIN_SIZE+VAL_SIZE
TEST_SPLIT  = DATASET_SIZE

# model related params
DEPTH_MULTIPLIER = 0.25
DROPOUT_PROB = 0.1
